import {cache} from "react";
import {initializeServerApp} from 'firebase/app';
import {getAuth} from "firebase/auth";
import {collection, doc, initializeFirestore} from 'firebase/firestore';
import firebaseConfig from "@/firebase-config";
import {createFirestoreRefs} from "shared/firestore-refs";
import type {CollectionReference, DocumentReference, QueryDocumentSnapshot} from 'firebase/firestore';


// Add ids when getting the data and removing when sending it
type WithId = { id: string };
const converter = <T extends WithId>() => ({
    toFirestore: ({ id: _id, ...data }: T) => data,
    fromFirestore: (snap: QueryDocumentSnapshot) => ({ ...snap.data(), id: snap.id }) as T,
});


// Initialize the DB given the user JWT token generated by Firebase
export const db = cache(async (userToken?: string) => {
    console.log(`Initializing client-side firestore with user token: ${userToken?.length}`);
    const app = initializeServerApp(firebaseConfig, {authIdToken: userToken});
    const auth = getAuth(app);
    if (userToken)
        await auth.authStateReady();
    const firestore = initializeFirestore(app, {ignoreUndefinedProperties: true});

    function dataPoint<T extends WithId>(collectionPath: string): CollectionReference<T>;
    function dataPoint<T extends WithId>(collectionPath: string, docPath: string): DocumentReference<T>;
    function dataPoint<T extends WithId>(collectionPath: string, docPath?: string) {
        const res = collection(firestore, collectionPath).withConverter(converter<T>());
        return docPath ? doc(res, docPath) : res;
    }

    return {
        ...createFirestoreRefs<'web'>(dataPoint),
        firestore: firestore,
    };
});

export default db;
